#!/bin/bash
#
# Install Git Hooks for Structure Enforcement
# This script sets up pre-commit and post-merge hooks
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Get project root (parent of .claude directory)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

echo "======================================"
echo "GIT HOOK INSTALLATION"
echo "======================================"
echo "Project root: $PROJECT_ROOT"

# Check if we're in a git repository
if [ ! -d "$PROJECT_ROOT/.git" ]; then
    echo -e "${RED}❌ Error: Not in a git repository${NC}"
    echo "Please run this from the project root"
    exit 1
fi

# Create hooks directory if it doesn't exist
HOOKS_DIR="$PROJECT_ROOT/.git/hooks"
if [ ! -d "$HOOKS_DIR" ]; then
    mkdir -p "$HOOKS_DIR"
    echo -e "${GREEN}✅ Created hooks directory${NC}"
fi

# Backup existing hooks if they exist
backup_hook() {
    local hook_name=$1
    local hook_path="$HOOKS_DIR/$hook_name"

    if [ -f "$hook_path" ] && [ ! -L "$hook_path" ]; then
        local backup_path="${hook_path}.backup.$(date +%Y%m%d_%H%M%S)"
        mv "$hook_path" "$backup_path"
        echo -e "${YELLOW}⚠️  Backed up existing $hook_name to $(basename $backup_path)${NC}"
    fi
}

# Install pre-commit hook
install_pre_commit() {
    echo ""
    echo "Installing pre-commit hook..."

    backup_hook "pre-commit"

    cat > "$HOOKS_DIR/pre-commit" << 'EOF'
#!/bin/bash
#
# Pre-commit hook for structure validation
# Generated by install-hooks.sh
#

# Get project root
PROJECT_ROOT="$(git rev-parse --show-toplevel)"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo "🔍 Validating project structure..."

# Check if validator script exists
VALIDATOR="$PROJECT_ROOT/.claude/scripts/structure_validator.py"
if [ ! -f "$VALIDATOR" ]; then
    echo -e "${YELLOW}⚠️  Structure validator not found - skipping validation${NC}"
    exit 0
fi

# Check if Python is available
if ! command -v python3 &> /dev/null; then
    echo -e "${YELLOW}⚠️  Python3 not found - skipping validation${NC}"
    exit 0
fi

# Run structure validation
python3 "$VALIDATOR" --mode pre-commit

RESULT=$?

if [ $RESULT -eq 0 ]; then
    echo -e "${GREEN}✅ Structure validation passed${NC}"
else
    echo -e "${RED}❌ Structure validation failed${NC}"
    echo ""
    echo "To fix automatically, run:"
    echo "  python3 .claude/scripts/auto-fix.py --apply"
    echo ""
    echo "To bypass this check (emergency only), use:"
    echo "  git commit --no-verify"
    exit $RESULT
fi
EOF

    chmod +x "$HOOKS_DIR/pre-commit"
    echo -e "${GREEN}✅ Pre-commit hook installed${NC}"
}

# Install commit-msg hook (enforce feature ID / IA reference)
install_commit_msg() {
    echo ""
    echo "Installing commit-msg hook..."

    backup_hook "commit-msg"

    cat > "$HOOKS_DIR/commit-msg" << 'EOF'
#!/bin/bash
#
# Commit message guard for traceability
#
MSG_FILE="$1"
MSG_CONTENT="$(cat "$MSG_FILE")"

# Allow merges and automated commits
if [[ "$MSG_CONTENT" =~ ^Merge ]] || [[ "$MSG_CONTENT" =~ ^Revert ]]; then
  exit 0
fi

# Opt-out switch
if [[ -n "$SKIP_COMMIT_MSG_CHECK" ]]; then
  echo "⚠️  Skipping commit-msg check due to SKIP_COMMIT_MSG_CHECK"
  exit 0
fi

# Require a feature/task/bug/struct ID
if ! echo "$MSG_CONTENT" | grep -Eiq '((FEATURE|TASK|BUG|STRUCT|BLOCKER)-[0-9]+)'; then
  echo "❌ Commit message missing feature/task ID (e.g., [STRUCT-ENFORCE-001] or FEATURE-123)."
  exit 1
fi

exit 0
EOF

    chmod +x "$HOOKS_DIR/commit-msg"
    echo -e "${GREEN}✅ Commit-msg hook installed${NC}"
}

# Install post-merge hook
install_post_merge() {
    echo ""
    echo "Installing post-merge hook..."

    backup_hook "post-merge"

    cat > "$HOOKS_DIR/post-merge" << 'EOF'
#!/bin/bash
#
# Post-merge hook for structure sync reminder
# Generated by install-hooks.sh
#

# Colors for output
YELLOW='\033[1;33m'
NC='\033[0m'

echo ""
echo -e "${YELLOW}📋 Reminder: Project structure may have changed${NC}"
echo "Run the following to check for structure violations:"
    echo "  python3 .claude/scripts/structure_validator.py"
echo "Or run smoke test (validator + dry-run auto-fix):"
    echo "  .claude/scripts/structure-smoke.sh"
echo ""
EOF

    chmod +x "$HOOKS_DIR/post-merge"
    echo -e "${GREEN}✅ Post-merge hook installed${NC}"
}

# Check Python dependencies
check_dependencies() {
    echo ""
    echo "Checking dependencies..."

    # Check Python version
    if command -v python3 &> /dev/null; then
        PYTHON_VERSION=$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
        echo -e "${GREEN}✅ Python $PYTHON_VERSION found${NC}"
    else
        echo -e "${RED}❌ Python3 not found - please install Python 3.7+${NC}"
        exit 1
    fi

    # Check required Python packages
    REQUIRED_PACKAGES="yaml"
    for package in $REQUIRED_PACKAGES; do
        if python3 -c "import $package" 2>/dev/null; then
            echo -e "${GREEN}✅ Python package '$package' found${NC}"
        else
            echo -e "${YELLOW}⚠️  Python package '$package' not found${NC}"
            echo "Install with: pip3 install pyyaml"
        fi
    done
}

# Test hook functionality
test_hooks() {
    echo ""
    echo "Testing hook installation..."

    # Test pre-commit hook
    if [ -x "$HOOKS_DIR/pre-commit" ]; then
        echo -e "${GREEN}✅ Pre-commit hook is executable${NC}"
    else
        echo -e "${RED}❌ Pre-commit hook is not executable${NC}"
        exit 1
    fi

    # Test post-merge hook
    if [ -x "$HOOKS_DIR/post-merge" ]; then
        echo -e "${GREEN}✅ Post-merge hook is executable${NC}"
    else
        echo -e "${RED}❌ Post-merge hook is not executable${NC}"
        exit 1
    fi
}

# Main installation flow
main() {
    install_pre_commit
    install_commit_msg
    install_post_merge
    check_dependencies
    test_hooks

    echo ""
    echo "======================================"
    echo -e "${GREEN}✅ GIT HOOKS INSTALLED SUCCESSFULLY${NC}"
    echo "======================================"
    echo ""
    echo "Hooks are now active. They will:"
    echo "  • Validate structure on every commit"
    echo "  • Remind about structure sync after merges"
    echo ""
    echo "To test the pre-commit hook, try:"
    echo "  touch test-file.tmp && git add test-file.tmp && git commit -m 'test'"
    echo ""
    echo "To uninstall hooks:"
    echo "  rm .git/hooks/pre-commit .git/hooks/post-merge"
}

# Run main installation
main
