#!/bin/bash
#
# Setup Cron Job for Nightly Cleanup
# This script installs a cron job to run Documentation Manager nightly
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Get project root
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

echo "======================================"
echo "CRON JOB SETUP"
echo "======================================"
echo "Project root: $PROJECT_ROOT"

# Check if running on production server (safety check)
if [ ! -z "$RAILWAY_ENVIRONMENT" ] || [ ! -z "$VERCEL" ]; then
    echo -e "${RED}❌ Error: Cannot setup cron on production server${NC}"
    echo "This script is for local development only"
    exit 1
fi

# Check if cron is available
if ! command -v crontab &> /dev/null; then
    echo -e "${RED}❌ Error: cron is not installed${NC}"
    echo "Please install cron for your operating system"
    exit 1
fi

# Create cron script
create_cron_script() {
    local cron_script="$PROJECT_ROOT/.claude/scripts/nightly-cleanup.sh"

    echo "Creating cron script..."

    cat > "$cron_script" << EOF
#!/bin/bash
#
# Nightly cleanup script
# Generated by setup-cron.sh
#

# Set up environment
export PATH="/usr/local/bin:/usr/bin:/bin:\$PATH"

# Change to project directory
cd "$PROJECT_ROOT"

# Log file
LOG_FILE="$PROJECT_ROOT/.claude/scripts/cron.log"

echo "[\$(date)] Starting nightly cleanup" >> "\$LOG_FILE"

# Run cleanup manager
if [ -f "$PROJECT_ROOT/.claude/scripts/cleanup-manager.py" ]; then
    python3 "$PROJECT_ROOT/.claude/scripts/cleanup-manager.py" --apply >> "\$LOG_FILE" 2>&1
    echo "[\$(date)] Cleanup completed with exit code: \$?" >> "\$LOG_FILE"
else
    echo "[\$(date)] Error: cleanup-manager.py not found" >> "\$LOG_FILE"
fi

# Rotate log if too large (>1MB)
if [ -f "\$LOG_FILE" ] && [ \$(stat -f%z "\$LOG_FILE" 2>/dev/null || stat -c%s "\$LOG_FILE" 2>/dev/null) -gt 1048576 ]; then
    mv "\$LOG_FILE" "\${LOG_FILE}.old"
    echo "[\$(date)] Log rotated" > "\$LOG_FILE"
fi
EOF

    chmod +x "$cron_script"
    echo -e "${GREEN}✅ Cron script created${NC}"
}

# Install cron job
install_cron_job() {
    local cron_script="$PROJECT_ROOT/.claude/scripts/nightly-cleanup.sh"
    local cron_entry="0 2 * * * $cron_script"

    echo ""
    echo "Installing cron job..."

    # Check if cron job already exists
    if crontab -l 2>/dev/null | grep -q "nightly-cleanup.sh"; then
        echo -e "${YELLOW}⚠️  Cron job already exists${NC}"
        echo "Current entry:"
        crontab -l | grep "nightly-cleanup.sh"
        echo ""
        read -p "Replace existing entry? (y/N): " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            echo "Keeping existing cron job"
            return
        fi
        # Remove existing entry
        crontab -l | grep -v "nightly-cleanup.sh" | crontab -
    fi

    # Add new cron job
    (crontab -l 2>/dev/null; echo "$cron_entry") | crontab -

    echo -e "${GREEN}✅ Cron job installed${NC}"
    echo "Scheduled to run daily at 2:00 AM"
}

# Show cron status
show_cron_status() {
    echo ""
    echo "Current cron jobs:"
    echo "=================="

    if crontab -l 2>/dev/null | grep -q "nightly-cleanup.sh"; then
        crontab -l | grep "nightly-cleanup.sh"
        echo ""
        echo -e "${GREEN}✅ Documentation Manager cron job is active${NC}"
    else
        echo -e "${YELLOW}⚠️  No Documentation Manager cron job found${NC}"
    fi
}

# Provide uninstall instructions
show_uninstall() {
    echo ""
    echo "To uninstall the cron job later, run:"
    echo "  crontab -l | grep -v 'nightly-cleanup.sh' | crontab -"
    echo ""
    echo "To view cron logs:"
    echo "  tail -f $PROJECT_ROOT/.claude/scripts/cron.log"
    echo ""
    echo "To run cleanup manually:"
    echo "  python3 $PROJECT_ROOT/.claude/scripts/cleanup-manager.py --preview"
}

# Main setup flow
main() {
    create_cron_script
    install_cron_job
    show_cron_status
    show_uninstall

    echo ""
    echo "======================================"
    echo -e "${GREEN}✅ CRON JOB SETUP COMPLETE${NC}"
    echo "======================================"
}

# Run main setup
main